#!/bin/bash
my name is vihaan
iam 5 years old
iam a tall boy
iam very active
i have so manu friends
iam now kinder garden
i love my parents
i love chicken
 i love to paly outside
my mom is my best friend
i love to wactching cartoon
my favorite cartoon is peppa pig
i love paw petrol
i love motu patulu cartoon
